---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: camel-ose-springboot-xml
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: camel-ose-springboot-xml@sha256:63ffc99e5d7c04236f4503b38d3887155b96753e3d61608ceb616e70f20db735
        namespace: fuselab
      name: latest
